-include ../../config.mk

SUBDIRS = common libdulge dulge-alternatives dulge-checkvers dulge-create dulge-fetch dulge-install dulge-query dulge-rindex dulge-uhelper dulge-remove dulge-digest

include ../../mk/subdir.mk
