TOPDIR = ../../../..
-include $(TOPDIR)/config.mk

TESTSSUBDIR = dulge/libdulge/config
TEST = config_test
EXTRA_FILES = Kyuafile dulge.cf dulge_nomatch.cf 1.include.cf 2.include.cf

include $(TOPDIR)/mk/test.mk
